#!/bin/bash

_pivpn() {
  local cur opts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  dashopts="-a -c -d -l -qr -r -h -u -up -bk -off -on"
  opts="agregar clientes, lista de depuración, códigos QR, eliminar, ayuda, desinstalar, actualizar"
  opts="${opts} backup (temp) off (temp) on"

  if [[ "${#COMP_WORDS[@]}" -eq 2 ]]; then
    if [[ "${cur}" == -* ]]; then
      COMPREPLY=("$(compgen -W "${dashopts}" -- "${cur}")")
    else
      COMPREPLY=("$(compgen -W "${opts}" -- "${cur}")")
    fi
  fi

  return 0
}

complete -F _pivpn pivpn
